CONNECT / AS SYSDBA
CREATE SPFILE FROM PFILE = 'inittcheprasovaelenap3402.ora';
STARTUP NOMOUNT;

CREATE DATABASE wetlaw
	LOGFILE GROUP 1 ('/u01/huk07/wetlaw/ora_control1.log') SIZE 100M,
			GROUP 2 ('/u01/huk07/wetlaw/ora_control2.log') SIZE 100M
	CHARACTER SET AL32UTF8
	NATIONAL CHARACTER SET AL16UTF16
	DATAFILE 
		'/u01/huk07/wetlaw/node01/oluke5.dbf' SIZE 150M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED,
		'/u01/huk07/wetlaw/node01/omozo48.dbf' SIZE 150M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
	SYSAUX DATAFILE '/u01/huk07/wetlaw/node02/fug40.dbf'
		SIZE 150M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
	DEFAULT TABLESPACE users DATAFILE '/u01/huk07/wetlaw/node02/ayetohi361.dbf'
		SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
	UNDO TABLESPACE undotbs1 DATAFILE '/u01/huk07/wetlaw/node02/undotbs.dbf'
		SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TABLESPACE GOOD_WHITE_BIRD DATAFILE
	'/u01/huk07/wetlaw/node04/goodwhitebird01.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED,
	'/u01/huk07/wetlaw/node01/goodwhitebird02.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED,
	'/u01/huk07/wetlaw/node04/goodwhitebird03.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

CREATE TABLESPACE BUSY_YELLOW_DATA DATAFILE
	'/u01/huk07/wetlaw/node01/busyyellowdata01.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED,
	'/u01/huk07/wetlaw/node04/busyyellowdata02.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED,
	'/u01/huk07/wetlaw/node04/busyyellowdata03.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED,
	'/u01/huk07/wetlaw/node01/busyyellowdata04.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

CREATE TABLESPACE DRY_BROWN_OVEN DATAFILE
	'/u01/huk07/wetlaw/node04/drybrownoven01.dbf' 
	SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

@?/rdbms/admin/catalog.sql
@?/rdbms/admin/catproc.sql
@?/sqlplus/admin/pupbld.sql