CREATE DATABASE wetlaw
	-- not comprehensive
	USER SYS IDENTIFIED BY 123
	USER SYSTEM IDENTIFIED BY 123

	-- character set
	CHARACTER SET AL32UTF8
	NATIONAL CHARACTER SET AL16UTF16

	-- system tablespace
	DATAFILE 
		'/u01/hek07/wetlaw/node01/oluke5.dbf' SIZE 150M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED,
		'/u01/hek07/wetlaw/node01/omozo48.dbf' SIZE 150M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED

	-- sysaux tablespace
	SYSAUX DATAFILE '/u01/hek07/wetlaw/node02/fug40.dbf'
		SIZE 150M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED

	-- users tablespace
	DEFAULT TABLESPACE users DATAFILE '/u01/hek07/wetlaw/node02/ayetohi361.dbf'
		SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
